name: Bless the code

on: 
  push: {}
  pull_request:
      branches:
        - master
        - v1.0.0
env:
  MIX_ENV: test
  ES_VERSION: 4

jobs:
  graph_conn:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.11.4', '1.12.2']
        erlang: ['22.3', '23.3', '24.0']

    services:
      es:
        image: eventstore/eventstore:release-5.0.10
        ports: ['1113:1113']
        env:
          EVENTSTORE_RUN_PROJECTIONS: "All"
          EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
          EVENTSTORE_CLUSTER_SIZE: 1
          EVENTSTORE_EXT_TCP_PORT: 1113
          EVENTSTORE_INSECURE: "true"
          EVENTSTORE_ENABLE_EXTERNAL_TCP: "true"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.erlang }}
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-deps-${{ matrix.elixir }}-${{ matrix.erlang }}-${{ hashFiles('mix.lock') }}
        restore-keys: ${{ runner.os }}-deps-${{ matrix.elixir }}-${{ matrix.erlang }}-
    - name: Install dependencies
      run: mix deps.get
    - name: Restore builds cache
      uses: actions/cache@v2
      with:
        path: _build/test
        key: ${{ runner.os }}-build_test-${{ matrix.elixir }}-${{ matrix.erlang }}-${{ hashFiles('mix.lock') }}
        restore-keys: ${{ runner.os }}-build_test-${{ matrix.elixir }}-${{ matrix.erlang }}-
    - name: Check warnings
      run: mix compile --warnings-as-errors --force
    - name: Run tests
      run: mix test --cover
